# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 857fa644ace62b3157abd564d1e19754de93bc339e3cce32027dbbf1b4d17147fdc7728791e6e2c9c0bec99c393bd14de07ca41d32d084066e3181b94034b593

test:
  secret_key_base: e9178e4698660405c550680bbddbc85026b20a7e03d6fc4c4106effd84203dd4f5917dd91581e227220b46683a848bf5b6b2a76d357688caca59c25d643d8086

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
